routes/web.php
<?php


/** Auth **/
Route::group(['as' => 'auth.'], function () {
	
	Route::get('/', 'Auth\LoginController@showLoginForm')->name('showLogin');
	Route::post('/', 'Auth\LoginController@login')->name('login');
	Route::post('/logout', 'Auth\LoginController@logout')->name('logout');
	Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

});




/** Dashboard **/
Route::group(['prefix'=>'dashboard', 'as' => 'dashboard.', 'middleware' => ['check.user_status', 'check.user_route']], function () {


	/** HOME **/	
	Route::get('/home', 'HomeController@index')->name('home');


	/** USER **/   
	Route::post('/user/activate/{slug}', 'UserController@activate')->name('user.activate');
	Route::post('/user/deactivate/{slug}', 'UserController@deactivate')->name('user.deactivate');
	Route::post('/user/logout/{slug}', 'UserController@logout')->name('user.logout');
	Route::get('/user/{slug}/reset_password', 'UserController@resetPassword')->name('user.reset_password');
	Route::patch('/user/reset_password/{slug}', 'UserController@resetPasswordPost')->name('user.reset_password_post');
	Route::resource('user', 'UserController');


	/** PROFILE **/
	Route::get('/profile', 'ProfileController@details')->name('profile.details');
	Route::patch('/profile/update_account_username/{slug}', 'ProfileController@updateAccountUsername')->name('profile.update_account_username');
	Route::patch('/profile/update_account_password/{slug}', 'ProfileController@updateAccountPassword')->name('profile.update_account_password');
	Route::patch('/profile/update_account_color/{slug}', 'ProfileController@updateAccountColor')->name('profile.update_account_color');


	/** MENU **/
	Route::resource('menu', 'MenuController');
	
});






/** Testing **/
Route::get('/dashboard/test', function(){

	return dd(Illuminate\Support\Str::random(16));

});

app/Models/User.php
<?php

namespace App\Models;

use Kyslik\ColumnSortable\Sortable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;



class User extends Authenticatable{




    use Notifiable, Sortable;

    protected $dates = ['created_at', 'updated_at', 'last_login_time'];

    public $sortable = ['username', 'firstname', 'is_online', 'is_active'];

    public $timestamps = false;

    protected $hidden = ['password', 'remember_token',];






    protected $attributes = [

        'slug' => '',
        'user_id' => '', 
        'email' => '', 
        'username' => '', 
        'password' => '', 
        'lastname' => '', 
        'middlename' => '', 
        'firstname' => '', 
        'position' => '', 
        'is_online' => false, 
        'is_active' => false,
        'color' => 'skin-green sidebar-mini', 
        'created_at' => null, 
        'updated_at' => null,
        'ip_created' => '',
        'ip_updated' => '',
        'user_created' => '',
        'user_updated' => '',
        'last_login_time' => null,
        'last_login_machine' => '',
        'last_login_ip' => '',

    ];






    /** RELATIONSHIPS **/ 
    public function userMenu() {
        return $this->hasMany('App\Models\UserMenu','user_id','user_id');
    }


    public function userSubmenu() {
        return $this->hasMany('App\Models\UserSubmenu','user_id','user_id');
    }
    

    



    /** GETTERS **/
    public function getFullnameShortAttribute(){
        return strtoupper(substr($this->firstname , 0, 1) . ". " . $this->lastname);
    }




    public function getFullnameAttribute(){
        return strtoupper($this->firstname . " " . substr($this->middlename , 0, 1) . ". " . $this->lastname);
    }
    







}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Core\Services\UserService;
use App\Http\Requests\User\UserFormRequest;
use App\Http\Requests\User\UserFilterRequest;
use App\Http\Requests\User\UserResetPasswordRequest;
use App\Http\Requests\User\UserSyncEmployeeRequest;


class UserController extends Controller{

       

    protected $user_service; 



    public function __construct(UserService $user_service){

        $this->user_service = $user_service;

    }




    public function index(UserFilterRequest $request){

        return $this->user_service->fetch($request);

    }

    


    public function create(){

        return view('dashboard.user.create');

    }

    


    public function store(UserFormRequest $request){

        return $this->user_service->store($request);

    }

    


    public function show($slug){

        return $this->user_service->show($slug);

    }

    


    public function edit($slug){

        return $this->user_service->edit($slug);

    }

    


    public function update(UserFormRequest $request, $slug){

        return $this->user_service->update($request, $slug);
        
    }

    


    public function destroy($slug){

        return $this->user_service->delete($slug);
        
    }




    public function activate($slug){

        return $this->user_service->activate($slug);
        
    }




    public function deactivate($slug){

        return $this->user_service->deactivate($slug);
        
    }




    public function logout($slug){

        return $this->user_service->logout($slug);
        
    }




    public function resetPassword($slug){

        return $this->user_service->resetPassword($slug);
        
    }




    public function resetPasswordPost(UserResetPasswordRequest $request, $slug){

        return $this->user_service->resetPasswordPost($request, $slug);
        
    }




    public function syncEmployee($slug){

        return $this->user_service->syncEmployee($slug);
        
    }




    public function syncEmployeePost(UserSyncEmployeeRequest $request, $slug){

        return $this->user_service->syncEmployeePost($request, $slug);
        
    }




    public function unsyncEmployee($slug){

        return $this->user_service->unsyncEmployee($slug);
        
    }




}

resources/views/dashboard/user/create.blade.php
@extends('layouts.admin-master')

@section('content')

<section class="content-header">
    <h1>Create User</h1>
</section>

<section class="content">
            
    <div class="box">
        
      <div class="box-header with-border">
        <h3 class="box-title">Form</h3>
        <div class="pull-right">
            <code>Fields with asterisks(*) are required</code>
        </div> 
      </div>
      
      <form id="user_create_form" class="form-horizontal" method="POST" autocomplete="off" action="{{ route('dashboard.user.store') }}">

        <div class="box-body">

          <div class="col-md-11">
                  
              @csrf

              {!! __form::textbox_inline(
                  'firstname', 'text', 'Firstname *', 'Firstname', old('firstname'), $errors->has('firstname'), $errors->first('firstname'), 'data-transform="uppercase"'
              ) !!}

              {!! __form::textbox_inline(
                  'middlename', 'text', 'Middlename *', 'Middlename', old('middlename'), $errors->has('middlename'), $errors->first('middlename'), 'data-transform="uppercase"'
              ) !!}

              {!! __form::textbox_inline(
                  'lastname', 'text', 'Lastname *', 'Lastname', old('lastname'), $errors->has('lastname'), $errors->first('lastname'), 'data-transform="uppercase"'
              ) !!}

              {!! __form::textbox_inline(
                  'email', 'email', 'Email *', 'Email', old('email'), $errors->has('email'), $errors->first('email'), ''
              ) !!}

              {!! __form::textbox_inline(
                  'position', 'text', 'Position *', 'Position / Plantilla', old('position'), $errors->has('position'), $errors->first('position'), 'data-transform="uppercase"'
              ) !!}

              {!! __form::textbox_inline(
                  'username', 'text', 'Username *', 'Username', old('username'), $errors->has('username') || Session::has('USER_CREATE_FAIL_USERNAME_EXIST'), $errors->first('username'), ''
              ) !!}

              {!! __form::password_inline(
                  'password', 'Password *', 'Password', $errors->has('password'), $errors->first('password'), ''
              ) !!}

              {!! __form::password_inline(
                  'password_confirmation', 'Confirm Password *', 'Confirm Password', '', '', ''
              ) !!}

          </div>


          {{-- USER MENU DYNAMIC TABLE GRID --}}
          <div class="col-md-12" style="padding-top:50px;">
            <div class="box box-solid">
              <div class="box-header with-border">
                <h3 class="box-title">User Menu</h3>
                <button id="add_row" type="button" class="btn btn-sm bg-green pull-right">Add Row &nbsp;<i class="fa fw fa-plus"></i></button>
              </div>
              
              <div class="box-body no-padding">
                
                <table class="table table-bordered">

                  <tr>
                    <th>Menus *</th>
                    <th>Menu Modules</th>
                    <th style="width: 40px"></th>
                  </tr>

                  <tbody id="table_body">

                    @if(old('menu'))
                      
                      @foreach(old('menu') as $key => $value)

                        <tr>

                          <td style="width:450px;">
                            <select name="menu[]" id="menu" class="form-control select2" style="width: 90%;">
                              <option value="">Select</option>
                              @foreach($global_menus_all as $data) 
                                  <option value="{{ $data->menu_id }}" {!! old('menu.'.$key) == $data->menu_id ? 'selected' : ''!!}>{{ $data->name }}</option>
                              @endforeach
                            </select>
                            <br><small class="text-danger">{{ $errors->first('menu.'.$key) }}</small>
                          </td>

                          <td style="min-width:50px; min-width:50px; max-width:50px">
                            <select name="submenu[]" id="submenu" class="form-control select2" multiple="multiple" data-placeholder="Modules" style="width: 80%;">
                                <option value="">Select</option>
                                @foreach($global_submenus_all as $data)
                                    @if(old('submenu') && $data->menu_id == old('menu.'.$key))
                                        <option value="{{ $data->submenu_id }}" {!! in_array($data->submenu_id, old('submenu')) ? 'selected' : '' !!}>{{$data->name}}</option>
                                    @else
                                        <option value="{{ $data->submenu_id }}">{{$data->name}}</option>
                                    @endif
                                @endforeach
                            </select>
                          </td>

                          <td>
                            <button id="delete_row" type="button" class="btn btn-sm bg-red"><i class="fa fa-times"></i></button>
                          </td>

                        </tr>

                      @endforeach

                    @endif

                    </tbody>
                </table>
               
              </div>

            </div>
          </div>

        </div>

        <div class="box-footer">
          <button type="submit" class="btn btn-default">Save <i class="fa fa-fw fa-save"></i></button>
        </div>

      </form>

    </div>

</section>

@endsection





@section('modals')

  @if(Session::has('USER_CREATE_SUCCESS'))

    {!! __html::modal(
      'user_create', '<i class="fa fa-fw fa-check"></i> Saved!', Session::get('USER_CREATE_SUCCESS')
    ) !!}

  @endif

@endsection 





@section('scripts')

  <script type="text/javascript">

  {!! __js::show_password('password', 'show_password') !!}
  {!! __js::show_password('password_confirmation', 'show_password_confirmation') !!}
  

  @if(Session::has('USER_CREATE_SUCCESS'))
    $('#user_create').modal('show');
  @endif


  {{-- ADD ROW --}}
  $(document).ready(function() {
    $("#add_row").on("click", function() {
        $('select').select2('destroy');
        var content ='<tr>' +
                      '<td style="width:450px;">' +
                        '<select name="menu[]" id="menu" class="form-control select2" style="width:90%;">' +
                          '<option value="">Select</option>' +
                          '@foreach($global_menus_all as $data)' +
                            '<option value="{{ $data->menu_id }}">{{ $data->name }}</option>' +
                          '@endforeach' +
                        '</select>' +
                      '</td>' +

                      '<td>' +
                        '<select name="submenu[]" id="submenu" class="form-control select2" multiple="multiple" data-placeholder="Modules" style="width:80%;">' +
                          '<option value="">Select</option>' +
                          '@foreach($global_submenus_all as $data)' +
                              '<option value="{{ $data->submenu_id }}">{{$data->name}}</option>' +
                          '@endforeach' +
                        '</select>' +

                      '</td>' +

                      '<td>' +
                          '<button id="delete_row" type="button" class="btn btn-sm bg-red"><i class="fa fa-times"></i></button>' +
                      '</td>' +
                    '</tr>';

      $("#table_body").append($(content));
      $('select').select2({width:400});
    });
  });





  {{-- AJAX Menu to Submenu--}}
  $(document).ready(function() {
    $(document).on("change", "#menu", function() {
        var key = $(this).val();
        var parent = $(this).closest('tr');
        console.log(parent);
        if(key) {
            $.ajax({
                headers: {"X-CSRF-TOKEN": $('meta[name="csrf-token"]').attr("content")},
                url: "/api/submenu/select_submenu_byMenuId/" + key,
                type: "GET",
                dataType: "json",
                success:function(data) {   

                    $(parent).find("#submenu").empty();

                    $.each(data, function(key, value) {
                        $(parent).find("#submenu").append("<option value='" + value.submenu_id + "'>"+ value.name +"</option>");
                    });

                    $(parent).find("#submenu").append("<option value>Select</option>");
        
                }
            });
        }else{
            $(parent).find("#submenu").empty();
        }
    });
  });





  {{-- AJAX Get Employee--}}
  // $(document).on("change", "#employee_sync", function () {

  //   var key = $(this).val();

  //   if(key){
  //     $.ajax({
  //       headers: {"X-CSRF-TOKEN": $('meta[name="csrf-token"]').attr("content")},
  //       url: "/api/user/response_from_employee/"+key,
  //       type: "GET",
  //       dataType: "json",
  //       success:function(data) {       
            
  //         $.each(data, function(key, value) {

  //           $("#user_create_form").find("input").not("input[name=_token]").val("");
  //           $("#user_create_form").find("input").not("input[name=_token]").removeAttr("readonly");

  //           if(value.firstname != ''){
  //             $("#user_create_form #firstname").val(value.firstname).attr("readonly", true);
  //           }

  //           if(value.middlename != ''){
  //             $("#user_create_form #middlename").val(value.middlename).attr("readonly", true);
  //           }

  //           if(value.lastname != ''){
  //             $("#user_create_form #lastname").val(value.lastname).attr("readonly", true);
  //           }

  //           if(value.email != ''){
  //             $("#user_create_form #email").val(value.email).attr("readonly", true);
  //           }

  //           if(value.position != ''){
  //             $("#user_create_form #position").val(value.position).attr("readonly", true);
  //           }
          
  //         });

  //       }
  //     });
  //   }else{
  //     $("#user_create_form").find("input").not("input[name=_token]").val("");
  //     $("#user_create_form").find("input").not("input[name=_token]").removeAttr("readonly");
  //   }
    
  // });




</script>
    
@endsection

resources/views/dashboard/user/index.blade.php
<?php

  $table_sessions = [ 
                      Session::get('USER_UPDATE_SUCCESS_SLUG'), 
                      Session::get('USER_ACTIVATE_SUCCESS_SLUG'),
                      Session::get('USER_DEACTIVATE_SUCCESS_SLUG'),
                      Session::get('USER_LOGOUT_SUCCESS_SLUG'),
                      Session::get('USER_RESET_PASSWORD_SUCCESS_SLUG'), 
                      Session::get('USER_SYNC_EMPLOYEE_SUCCESS_SLUG'),  
                      Session::get('USER_UNSYNC_EMPLOYEE_SUCCESS_SLUG'), 
                    ];

  $appended_requests = [
                        'q'=> Request::get('q'), 
                        'sort' => Request::get('sort'),
                        'direction' => Request::get('direction'),

                        'ol' => Request::get('ol'), 
                        'a' => Request::get('a'),
                      ];

  $span_check = '<span class="badge bg-green"><i class="fa fa-check "></i></span>';
  $span_times = '<span class="badge bg-red"><i class="fa fa-times "></i></span>';

?>





@extends('layouts.admin-master')

@section('content')
    
  <section class="content-header">
      <h1>User List</h1>
  </section>

  <section class="content">
    
    {{-- Form Start --}}
    <form data-pjax class="form" id="filter_form" method="GET" autocomplete="off" action="{{ route('dashboard.user.index') }}">

    {{-- Advance Filters --}}
    {!! __html::filter_open() !!}

      {!! __form::select_static_for_filter(
        '2', 'ol', 'Login Status', old('ol'), ['Online' => 'true', 'Offline' => 'false'], 'submit_user_filter', '', ''
      ) !!}

      {!! __form::select_static_for_filter(
        '2', 'a', 'User Status', old('a'), ['Active' => 'true', 'Inactive' => 'false'], 'submit_user_filter', '', ''
      ) !!}

    {!! __html::filter_close('submit_user_filter') !!}


    <div class="box" id="pjax-container" style="overflow-x:auto;">

      {{-- Table Search --}}        
      <div class="box-header with-border">
        {!! __html::table_search(route('dashboard.user.index')) !!}
      </div>

    {{-- Form End --}}  
    </form>

      {{-- Table Grid --}}        
      <div class="box-body no-padding">
        <table class="table table-hover">
          <tr>
            <th>@sortablelink('username', 'Username')</th>
            <th>@sortablelink('firstname', 'Name')</th>
            <th>@sortablelink('is_online', 'Online')</th>
            <th>@sortablelink('is_active', 'Active')</th>
            <th style="width: 150px">Action</th>
          </tr>
          @foreach($users as $data) 
            <tr {!! __html::table_highlighter( $data->slug, $table_sessions)!!}>
              <td>{{ $data->username }}</td>
              <td>{{ $data->fullname }}</td>
              <td>{!! $data->is_online == 1 ?  $span_check : $span_times !!}</td>
              <td>{!! $data->is_active == 1 ? $span_check : $span_times !!}</td>
              <td>
                <select id="action" class="form-control input-md">
                  <option value="">Select</option>
                  <option data-type="1" data-url="{{ route('dashboard.user.show', $data->slug) }}">Details</option>
                  <option data-type="1" data-url="{{ route('dashboard.user.edit', $data->slug) }}">Edit</option>
                  <option data-type="0" data-action="delete" data-url="{{ route('dashboard.user.destroy', $data->slug) }}">Delete</option>
                  
                  @if($data->is_active == 1 && $data->is_online == 1)
                    <option data-type="0" data-action="logout" data-url="{{ route('dashboard.user.logout', $data->slug) }}">Logout</option>
                  @endif 
                  
                  @if($data->is_active == 0)
                    <option data-type="0" data-action="activate" data-url="{{ route('dashboard.user.activate', $data->slug) }}">Activate</option>
                  @else
                    <option data-type="0" data-action="deactivate" data-url="{{ route('dashboard.user.deactivate', $data->slug) }}">Deactivate</option>
                  @endif

                  <option data-type="1" data-action="reset_password" data-url="{{ route('dashboard.user.reset_password', $data->slug) }}">Reset Password</option>

                </select>
              </td>
            </tr>
            @endforeach
          </table>
      </div>

      @if($users->isEmpty())
        <div style="padding :5px;">
          <center><h4>No Records found!</h4></center>
        </div>
      @endif

      <div class="box-footer">
        {!! __html::table_counter($users) !!}
        {!! $users->appends($appended_requests)->render('vendor.pagination.bootstrap-4')!!}
      </div>

    </div>

  </section>

  <form id="from_user_logout" method="POST" style="display: none;">
    @csrf
  </form>

  <form id="from_user_activate" method="POST" style="display: none;">
    @csrf
  </form>

  <form id="from_user_deactivate" method="POST" style="display: none;">
    @csrf
  </form>

@endsection






@section('modals')

  {!! __html::modal_delete('user_delete') !!}

@endsection 






@section('scripts')

  <script type="text/javascript">

    {{-- CALL CONFIRM DELETE MODAL --}}
    {!! __js::modal_confirm_delete_caller('user_delete') !!}


    {{-- CALL LOGOUT FORM --}}
    {!! __js::form_submitter_via_action('logout', 'from_user_logout') !!}


    {{-- CALL ACTIVATE FORM --}}
    {!! __js::form_submitter_via_action('activate', 'from_user_activate') !!}


    {{-- CALL DEACTIVATE FORM --}}
    {!! __js::form_submitter_via_action('deactivate', 'from_user_deactivate') !!}


    {{-- UPDATE TOAST --}}
    @if(Session::has('USER_UPDATE_SUCCESS'))
      {!! __js::toast(Session::get('USER_UPDATE_SUCCESS')) !!}
    @endif


    {{-- DELETE TOAST --}}
    @if(Session::has('USER_DELETE_SUCCESS'))
      {!! __js::toast(Session::get('USER_DELETE_SUCCESS')) !!}
    @endif


    {{-- LOGOUT TOAST --}}
    @if(Session::has('USER_LOGOUT_SUCCESS'))
      {!! __js::toast(Session::get('USER_LOGOUT_SUCCESS')) !!}
    @endif


    {{-- ACTIVATE TOAST --}}
    @if(Session::has('USER_ACTIVATE_SUCCESS'))
      {!! __js::toast(Session::get('USER_ACTIVATE_SUCCESS')) !!}
    @endif


    {{-- DEACTIVATE TOAST --}}
    @if(Session::has('USER_DEACTIVATE_SUCCESS'))
        {!! __js::toast(Session::get('USER_DEACTIVATE_SUCCESS')) !!}
    @endif


    {{-- RESET PASSWORD SUCCESS TOAST --}}
    @if(Session::has('USER_RESET_PASSWORD_SUCCESS'))
        {!! __js::toast(Session::get('USER_RESET_PASSWORD_SUCCESS')) !!}
    @endif


    {{-- SYNC EMPLOYEE SUCCESS TOAST --}}
    @if(Session::has('USER_SYNC_EMPLOYEE_SUCCESS'))
        {!! __js::toast(Session::get('USER_SYNC_EMPLOYEE_SUCCESS')) !!}
    @endif


    {{-- UNSYNC EMPLOYEE SUCCESS TOAST --}}
    @if(Session::has('USER_UNSYNC_EMPLOYEE_SUCCESS'))
        {!! __js::toast(Session::get('USER_UNSYNC_EMPLOYEE_SUCCESS')) !!}
    @endif

  </script>
    
@endsection

resources/views/dashboard/user/reset_password.blade.php
@extends('layouts.admin-master')

@section('content')

<section class="content-header">
  <h1>User Reset Password</h1>
  <div class="pull-right" style="margin-top: -25px;">
    {!! __html::back_button(['dashboard.user.index']) !!}
  </div>
</section>

<section class="content">
            
    <div class="box">
        
      <div class="box-header with-border">
        <h3 class="box-title">Form</h3>
      </div>
      
      <form class="form-horizontal">

        <div class="box-body">

          @if(Session::has('USER_RESET_PASSWORD_CONFIRMATION_FAIL'))
            {!! __html::alert('danger', '<i class="icon fa fa-ban"></i> Alert!', Session::get('USER_RESET_PASSWORD_CONFIRMATION_FAIL')) !!}
          @endif

          @if(Session::has('USER_RESET_PASSWORD_OWN_ACCOUNT_FAIL'))
            {!! __html::alert('danger', '<i class="icon fa fa-ban"></i> Alert!', Session::get('USER_RESET_PASSWORD_OWN_ACCOUNT_FAIL')) !!}
          @endif

          <div class="col-md-11">
                  
              @csrf    

              {!! __form::password_inline(
                  'password', 'New Password', 'New Password', $errors->has('password'), $errors->first('password'), ''
              ) !!}

              {!! __form::password_inline(
                  'password_confirmation', 'Confirm Password', 'Confirm Password', '', '', ''
              ) !!}

          </div>

        </div>

      </form>

      <div class="box-footer">
          <button class="btn btn-success" id="reset_button">Reset <i class="fa fa-fw fa-refresh"></i></button>
      </div>

    </div>

</section>

@endsection





    
@section('modals')

  {{-- USER RESET CONFIRMATION MODAL --}}  
  <div class="modal fade" id="user_reset_password" data-backdrop="static">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button class="close" data-dismiss="modal">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title"><i class="fa fa-key"></i> &nbsp;User Confirmation</h4>
        </div>
        <div class="modal-body">
          <form id="reset_password_form" class="form-horizontal" method="POST" autocomplete="off" action="{{ route('dashboard.user.reset_password_post', $user->slug) }}">
            @csrf
            <input name="_method" value="PATCH" type="hidden">
            <p style="font-size: 17px;">Confirm first your identity before resetting someone's password!</p><br>
            <input id="password_in_modal" type="hidden" name="password" value="">
            <input id="password_confirmation_in_modal" type="hidden" name="password_confirmation" value="">

            {!! __form::textbox_inline(
                'username', 'text', 'Username', 'Username', old('username'), $errors->has('username'), $errors->first('username'), ''
            ) !!}

            {!! __form::password_inline(
                'user_password', 'Password', 'Password', $errors->has('user_password'), $errors->first('user_password'), ''
            ) !!}

        </div>

        <div class="modal-footer">
          <button class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-success">Sign-in</button>
        </div>

        </form>

      </div>
    </div>
  </div>

@endsection






@section('scripts')

  <script type="text/javascript">

    {!! __js::show_password('password', 'show_password') !!}
    {!! __js::show_password('password_confirmation', 'show_password_confirmation') !!}
    {!! __js::show_password('user_password', 'show_user_password') !!}

    {{-- CALL RESET PASSWORD CONFIRMATION MODAL --}}
    $(document).on("click", "#reset_button", function () {
      var password = $("#password").val();
      var password_confirmation = $("#password_confirmation").val();
      $("#user_reset_password").modal("show");
      $("#reset_password_form #password_in_modal").attr("value", password);
      $("#reset_password_form #password_confirmation_in_modal").attr("value", password_confirmation);
    });

  </script>
    
@endsection