routes/web.php
<?php


/** Auth **/
Route::group(['as' => 'auth.'], function () {
	
	Route::get('/', 'Auth\LoginController@showLoginForm')->name('showLogin');
	Route::post('/', 'Auth\LoginController@login')->name('login');
	Route::post('/logout', 'Auth\LoginController@logout')->name('logout');
	Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

});




/** Dashboard **/
Route::group(['prefix'=>'dashboard', 'as' => 'dashboard.', 'middleware' => ['check.user_status', 'check.user_route']], function () {


	/** HOME **/	
	Route::get('/home', 'HomeController@index')->name('home');


	/** USER **/   
	Route::post('/user/activate/{slug}', 'UserController@activate')->name('user.activate');
	Route::post('/user/deactivate/{slug}', 'UserController@deactivate')->name('user.deactivate');
	Route::post('/user/logout/{slug}', 'UserController@logout')->name('user.logout');
	Route::get('/user/{slug}/reset_password', 'UserController@resetPassword')->name('user.reset_password');
	Route::patch('/user/reset_password/{slug}', 'UserController@resetPasswordPost')->name('user.reset_password_post');
	Route::resource('user', 'UserController');


	/** PROFILE **/
	Route::get('/profile', 'ProfileController@details')->name('profile.details');
	Route::patch('/profile/update_account_username/{slug}', 'ProfileController@updateAccountUsername')->name('profile.update_account_username');
	Route::patch('/profile/update_account_password/{slug}', 'ProfileController@updateAccountPassword')->name('profile.update_account_password');
	Route::patch('/profile/update_account_color/{slug}', 'ProfileController@updateAccountColor')->name('profile.update_account_color');


	/** MENU **/
	Route::resource('menu', 'MenuController');
	
});






/** Testing **/
Route::get('/dashboard/test', function(){

	return dd(Illuminate\Support\Str::random(16));

});

resources/views/layouts/admin-master.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Laravel AdminLTE</title>
    <link rel="shortcut icon" href="{{ asset('favicon.png') }}">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    @include('layouts.css-plugins')

  </head>
  <body class="hold-transition {!! Auth::check() ? __sanitize::html_encode(Auth::user()->color) : '' !!}">

    <div id="loader"></div>

    <div class="wrapper">

      @include('layouts.admin-topnav')

      @include('layouts.admin-sidenav') 

      <div class="content-wrapper" style="height:500em;"> 

        @yield('content')

      </div>

      <footer class="main-footer">
        <div class="pull-right hidden-xs">
          <b>Version</b> 1.1.0
        </div>
        <strong>Copyright &copy; 2018-2019 <a href="#">toomelette</a>.</strong> All rights
        reserved.
      </footer>

    </div>

    @include('layouts.js-plugins')
    
    @yield('modals')

    @yield('scripts')

  </body>

</html>

resources/views/layouts/admin-sidenav.blade.php
<aside class="main-sidebar">
  <section class="sidebar">
    <div class="user-panel">
      <div class="pull-left image">
        <img src="{{ asset('images/avatar.jpeg') }}" class="img-circle" alt="User Image">
      </div>
      <div class="pull-left info">
        
        @if(Auth::check())
          <p>{{ Auth::user()->firstname }}</p>
        @endif

        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
      </div>
    </div>
    <ul class="sidebar-menu" data-widget="tree">
      

      @if(Auth::check())


        @if(!$global_user_menus->isEmpty())

            <li class="header">Navigation</li>
            @foreach($global_user_menus as $user_menu)

              @if($user_menu->is_menu == true)

                @if($user_menu->is_dropdown == false)

                <li class="{!! Route::currentRouteNamed($user_menu->route) ? 'active' : '' !!}">
                  <a href="{{ route($user_menu->route) }}">
                    <i class="fa {{ $user_menu->icon }}"></i> <span>{{ $user_menu->name }}</span>
                  </a>
                </li>

                @else

                  <li class="treeview {!! Route::currentRouteNamed($user_menu->route) ? 'active' : '' !!}">
                    <a href="#">
                      <i class="fa {{ $user_menu->icon }}"></i> <span>{{ $user_menu->name }}</span>
                      <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                      </span>
                    </a>

                      <ul class="treeview-menu">

                        @foreach($user_menu->userSubMenu as $user_nav)

                          @if($user_nav->is_nav == true)

                            <li class="{!! Route::currentRouteNamed($user_nav->route) ? 'active' : '' !!}">
                              <a href="{{ route($user_nav->route) }}"><i class="fa fa-caret-right"></i> {{ $user_nav->name }}</a>
                            </li>

                          @endif

                        @endforeach

                      </ul>

                  </li>

                @endif

              @endif

            @endforeach

          @endif
          
      @endif

    </ul>
  </section>
</aside>

resources/views/layouts/admin-topnav.blade.php
<header class="main-header">
  <a href="#" class="logo">
    <span class="logo-mini">L</span>
    <span class="logo-lg"><b>Laravel AdminLTE</b></span>
  </a>
  <nav class="navbar navbar-static-top">
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </a>
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <img src="{{asset('images/avatar.jpeg')}}" class="user-image" alt="User Image">
            @if(Auth::check())
              {{ __sanitize::html_encode(Auth::user()->firstname) }}
            @endif
          </a>
          <ul class="dropdown-menu">
            <li class="user-header">
              <img src="{{asset('images/avatar.jpeg')}}" class="img-circle" alt="User Image">
              <p>
                @if(Auth::check())
                  {{ __sanitize::html_encode(Auth::user()->firstname) .' '. __sanitize::html_encode(Auth::user()->lastname) }}
                  <small>{{ __sanitize::html_encode(Auth::user()->position) }}</small>
                @endif
                
              </p>
            </li>
            <li class="user-footer">
              <div class="pull-left">
                <a href="{{ route('dashboard.profile.details') }}" class="btn btn-default btn-flat">Profile</a>
              </div>
              <div class="pull-right">
                <a  href="{{ route('auth.logout') }}" onclick="event.preventDefault(); document.getElementById('frm-logout').submit();" class="btn btn-default btn-flat">Sign out</a>
              </div>
              <form id="frm-logout" action="{{ route('auth.logout') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
              </form>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

resources/views/layouts/css-plugins.blade.php
<link rel="stylesheet" type="text/css" href="{{ asset('template2/bower_components/bootstrap/css/bootstrap.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('template2/assets/pages/waves/css/waves.min.css') }}" media="all">
<link rel="stylesheet" type="text/css" href="{{ asset('template2/assets/pages/prism/prism.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('template2/assets/icon/feather/css/feather.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('template2/assets/icon/themify-icons/themify-icons.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('template2/assets/icon/icofont/css/icofont.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('template2/assets/icon/font-awesome/css/font-awesome.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('template2/assets/css/style.css') }}">    

resources/views/layouts/guest-master.blade.php
<!DOCTYPE html>
<html lang="en">
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Laravel Admindek</title>
  <link rel="shortcut icon" href="{{ asset('favicon.png') }}">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Quicksand:500,700" rel="stylesheet">
  @include('layouts.css-plugins')
</head>
<body>
  <div class="loader-bg">
    <div class="loader-bar"></div>
  </div>
  <div id="pcoded" class="pcoded">
    <div class="pcoded-overlay-box"></div>
    
    {{-- NAVIGATION --}}
    <div class="pcoded-container navbar-wrapper">
      <nav class="navbar header-navbar pcoded-header">
        <div class="navbar-wrapper">
          <div class="navbar-logo">
            <a href="#" style="font-size:17px;">Laravel Admindek</a>
          </div>
          <div class="navbar-container container-fluid">
            <ul class="nav-left">
              <li>
                <a href="#" onclick="javascript:toggleFullScreen()" class="waves-effect waves-light">
                  <i class="full-screen feather icon-maximize"></i>
                </a>
              </li>
            </ul>
            <ul class="nav-right">
              <li class="header-notification">
                <div class="dropdown-primary dropdown">
                  <a href="#">Login</a>
                </div>
              </li>
              <li class="header-notification">
                <div class="dropdown-primary dropdown">
                  <a href="#">Info</a>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>

    {{-- BODY --}}
    <div class="pcoded-main-container">
      <div class="pcoded-wrapper">
        <div class="pcoded-content">
          <div class="pcoded-inner-content">
            <div class="main-body">
              <div class="page-wrapper">
                <div class="page-body">
                  @yield('content')
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
  @include('layouts.js-plugins')
  <script type="text/javascript" src="{{ asset('template2/assets/js/vertical/menu/menu-hori-fixed.js') }}"></script>
</body>
</html>

resources/views/layouts/js-plugins.blade.php
<script type="text/javascript" src="{{ asset('template2/bower_components/jquery/js/jquery.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('template2/bower_components/jquery-ui/js/jquery-ui.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('template2/bower_components/jquery-slimscroll/js/jquery.slimscroll.js') }}"></script>
<script type="text/javascript" src="{{ asset('template2/bower_components/popper.js/js/popper.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('template2/bower_components/bootstrap/js/bootstrap.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('template2/bower_components/modernizr/js/modernizr.js') }}"></script>
<script type="text/javascript" src="{{ asset('template2/bower_components/modernizr/js/css-scrollbars.js') }}"></script>

<script type="text/javascript" src="{{ asset('template2/assets/pages/waves/js/waves.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('template2/assets/pages/prism/custom-prism.js') }}"></script>

<script type="text/javascript" src="{{ asset('template2/assets/js/pcoded.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('template2/assets/js/vertical/vertical-layout.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('template2/assets/js/script.min.js') }}"></script>